CATEGORIES = {

    "Celulares": {
        "iphone": 30,
        "apple": 28,
        "ios": 20,
        "galaxy": 28,
        "samsung": 25,
        "xiaomi": 25,
        "redmi": 22,
        "poco": 22,
        "realme": 22,
        "motorola": 22,
        "moto g": 22,
        "moto e": 20,
        "smartphone": 20,
        "celular": 20,
        "5g": 10,
        "dual chip": 8,
        "nfc": 8,
        "amoled": 8,
        "oled": 8,
        "película": 10,
        "pelicula": 10,
        "capa": 10,
        "capinha": 10,
        "carregador": 8,
        "cabo usb": 8,
        "usb c": 8,
        "power bank": 10,
        "pelicula 3d": 12,
        "pelicula vidro": 12,
        "suporte celular": 8,
        "tripé celular": 8,
        "ring light": 6,
        "selfie": 6,
        "fone iphone": 8,
        "fone samsung": 8,
        "fone bluetooth": 8,
    },

    "Informática": {
        "notebook": 30,
        "ultrabook": 25,
        "chromebook": 22,
        "pc": 18,
        "desktop": 18,
        "computador": 20,
        "monitor": 25,
        "ssd": 25,
        "hd": 20,
        "hd externo": 20,
        "memória ram": 22,
        "ram": 18,
        "placa mãe": 20,
        "placa mae": 20,
        "processador": 25,
        "intel": 15,
        "amd": 15,
        "ryzen": 20,
        "core i3": 20,
        "core i5": 22,
        "core i7": 24,
        "core i9": 26,
        "mouse": 10,
        "teclado": 10,
        "webcam": 15,
        "impressora": 22,
        "scanner": 20,
        "roteador": 20,
        "router": 20,
        "switch": 15,
        "modem": 18,
        "pendrive": 18,
        "adaptador usb": 15,
        "hub usb": 15,
        "fonte atx": 18,
        "gabinete": 18,
        "cooler": 18,
        "water cooler": 22,
    },

    "Gamer": {
        "gamer": 35,
        "rgb": 12,
        "headset": 25,
        "mouse gamer": 30,
        "teclado gamer": 30,
        "cadeira gamer": 35,
        "controle": 18,
        "joystick": 25,
        "volante gamer": 30,
        "playstation": 25,
        "ps5": 30,
        "ps4": 25,
        "xbox": 30,
        "series s": 22,
        "series x": 22,
        "nintendo": 25,
        "switch oled": 30,
        "switch": 22,
        "logitech g": 30,
        "redragon": 30,
        "hyperx": 30,
        "razer": 30,
        "corsair": 28,
        "steelseries": 28,
        "cadeira rgb": 15,
        "mousepad gamer": 20,
        "placa de captura": 18,
        "stream": 18,
    },

    "Eletrônicos": {
        "tv": 25,
        "smart tv": 30,
        "android tv": 25,
        "google tv": 25,
        "fire tv": 25,
        "projetor": 25,
        "caixa de som": 20,
        "soundbar": 25,
        "home theater": 25,
        "bluetooth": 10,
        "microfone": 20,
        "camera": 20,
        "câmera": 20,
        "drone": 25,
        "gps": 18,
        "smartwatch": 20,
        "smart band": 20,
        "relógio inteligente": 20,
        "echo dot": 18,
        "alexa": 18,
        "kindle": 18,
    },

    "Casa": {
        "ventilador": 25,
        "aspirador": 25,
        "vassoura": 18,
        "rodo": 15,
        "balde": 15,
        "organizador": 18,
        "cabide": 15,
        "cortina": 18,
        "tapete": 18,
        "almofada": 18,
        "edredom": 18,
        "colchão": 20,
        "travesseiro": 18,
        "guarda roupa": 20,
        "armário": 18,
        "estante": 18,
        "mesa": 18,
        "cadeira": 15,
        "sofá": 20,
        "espelho": 18,
    },

    "Cozinha": {
        "air fryer": 35,
        "fritadeira": 25,
        "liquidificador": 30,
        "cafeteira": 30,
        "batedeira": 25,
        "panela": 22,
        "panela elétrica": 30,
        "panela eletrica": 30,
        "cooktop": 25,
        "forno": 22,
        "microondas": 25,
        "micro-ondas": 25,
        "geladeira": 25,
        "freezer": 22,
        "espremedor": 20,
        "processador de alimentos": 25,
        "sanduicheira": 22,
        "grill": 20,
        "garrafa térmica": 18,
        "talher": 15,
    },

    "Beleza": {
        "perfume": 25,
        "hidratante": 20,
        "maquiagem": 25,
        "batom": 22,
        "base": 20,
        "corretivo": 20,
        "máscara": 18,
        "mascara": 18,
        "shampoo": 22,
        "condicionador": 22,
        "secador": 20,
        "chapinha": 22,
        "escova secadora": 25,
        "barbeador": 22,
        "depilador": 22,
        "creme": 18,
    },

    "Moda": {
        "camiseta": 20,
        "camisa": 20,
        "calça": 20,
        "calca": 20,
        "bermuda": 18,
        "short": 18,
        "vestido": 22,
        "saia": 18,
        "blusa": 18,
        "jaqueta": 20,
        "casaco": 20,
        "moletom": 20,
        "tênis": 22,
        "tenis": 22,
        "sapato": 22,
        "chinelo": 18,
        "sandália": 18,
        "sandalia": 18,
        "bolsa": 20,
        "mochila": 18,
        "boné": 18,
        "bone": 18,
        "relógio": 18,
        "relogio": 18,
    },

    "Pets": {
        "ração": 30,
        "racao": 30,
        "cachorro": 25,
        "gato": 25,
        "pet": 20,
        "coleira": 20,
        "guia": 18,
        "comedouro": 18,
        "bebedouro": 18,
        "arranhador": 22,
        "areia": 18,
        "brinquedo pet": 18,
        "casinha": 20,
        "tapete higiênico": 25,
        "tapete higienico": 25,
    },

    "Infantil": {
        "bebê": 25,
        "bebe": 25,
        "mamadeira": 25,
        "chupeta": 22,
        "fralda": 25,
        "berço": 25,
        "berco": 25,
        "carrinho": 22,
        "cadeira alimentação": 22,
        "brinquedo": 20,
        "lego": 18,
        "boneca": 20,
        "carrinho infantil": 20,
    },

    "Esportes": {
        "bicicleta": 25,
        "halter": 22,
        "peso": 18,
        "academia": 22,
        "esteira": 25,
        "elástico": 18,
        "elastico": 18,
        "yoga": 18,
        "pilates": 18,
        "bola": 18,
        "futebol": 18,
        "basquete": 18,
        "vôlei": 18,
        "volei": 18,
        "luva": 18,
        "capacete": 20,
        "patins": 20,
        "skate": 20,
    }

}